### PR TITLE
Alternative: remove reapers

### PR DESCRIPTION
**Pull request by t0yv0**
@brendanhay @rohanmc 

With these changes, my ml-api local leak is resolved. However there might be some adverse effects, we need to be careful..

What I did is I removed reapers and rolled my own agent that owns the UDP socket.

Advantages:

- agent does error recovery by wait/reconnect
- buffer size is bounded by one metrics line

Disadvantages:

- higher syncronization overhead (MVar vs IORef)
- more synchronization events (on /every/ metric send invocation)
- threads that send metrics can block, especially if agent is waiting to recover from io-exception
- more syscalls (writing to socket line-by-line, not larger chunks as before)
- runUtf8Builder runs more often (once per line now), can have a cost

Thoughts?

To improve the blocked writer thread scenario I can rearrange the agent a bit to pull and drop messages from writer threads while it is waiting a second before retrying socket connectivity.

### CODE REVIEW

**Comment by brendanhay** [comment]
A couple of observations:

* The `MVar` is a channel for sending data to the handle. A `Handle` is actually an `MVar`. Probably what we want to use here is a `TVar` since it (may) lower the writer synchronization overhead.
* The use of `forkIO` and `withRestarts` is unsafe in the presence of (asynchronous) exceptions. You should look into both [async](hackage.haskell.org/package/async) and [immortal](hackage.haskell.org/package/immortal), with `async` (always) being a better choice than using `forkIO` if you can wait on the result of the `Async a` and subsequently have the exceptions thrown in the waiting thread, and `immortal` being more of a direct translation (+ safety) of what you have here.

Aside from those notes about the concurrency primitives, it looks good.

Orthogonally we are looking into standardising our metrics, monitoring, and logging libraries on platform. Looking at the `datadog` codebase - it probably makes sense longer term to just throw it away and write something conceptually simpler (morally what you've done here) and worry about things like reapers/buffering etc. when we have metrics .. for the metrics, in place.

**Comment by t0yv0** [comment]
Whoah so a Handle is thread-safe, I did not know that. If that is the case don't need a thread to guard it? Just write bytestrings as soon as they're produced?

My only motivation for synchronization here was assuming that if multiple threads to hPut on a Handle then *bad things would happen*, as they would in F#.

Ugh async exceptions.

> morally what you've done here

I'd be for that, just afraid it's not going to happen unless we move fast and throw some skunkwork overtime to get there.

It would be good if we could keep a stable interface that separates instrumenting and and sending the metrics from where they go. So we don't have to make too many source changes to application code when swapping different backends.

metrics for the metrics lol

**Comment by brendanhay** [comment]
Handle is defined [here](http://hackage.haskell.org/package/base-4.10.1.0/docs/src/GHC.IO.Handle.Types.html#Handle), so the underlying `MVar` would ensure that whatever unit you're writing is handled atomically - this means that as long as you're _writing the entire line_ - it'll work, but if you write piecemeal then other threads output will interleave.

**Comment by t0yv0** [comment]
Playing with it some more, mostly for my own education.

`async` library is very nice it takes care of "linked" threads like Erlang spawn_link. With catching only IOException, and doing sleep/flush in parallel I get my program to behave as I expect - I'm testing with running statsd and crashing it in parallel. The program survives statsd crashes and socket errors and does not block writers during those.

Why/how would you use a TVar? I did not quite get that comment you had.

An MVar is a channel between the writers and the agent thread that guards the Handle. The agent thread does graceful restart/reconnect. One line of output travels through MVar at a time.

Based on this:

https://stackoverflow.com/questions/15439966/when-why-use-an-mvar-over-a-tvar

TVar is slower and also is not quite a channel?

We could dispense with agent layer and write to Handle directly. Possibly much more efficient. But then the user or something out there has to handle IOExceptions. I guess if statsd daemon was rocksolid and we did not worry about it we could just let the entire API fail on IOException from sending the metrics and have the process (or even box) restart.

**Comment by t0yv0** [comment]
I played some more.. Looks like reopening Socket is really unnecessary. Just writing to the same handle will start working if statsd service goes up. So the extra layer of sync is too complicated. Closing.

**Pull request closed without merging**
